"""
Purpose: Provide a decision-first executive dashboard experience consuming all agent outputs.
Inputs: JSON outputs under outputs/ generated by discovery, waste, renewal, scenario, savings, and executive summary agents.
Outputs: Streamlit interactive dashboard with overview metrics, savings opportunities, scenario comparison, and executive narrative.
Assigned Team Member: RYAN
Dependencies: streamlit, json, pathlib, pandas.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st


BASE_DIR = Path(__file__).resolve().parents[1]
OUTPUT_DIR = BASE_DIR / "outputs"


st.set_page_config(page_title="Infra Spend Intelligence - Executive Dashboard", layout="wide")


def read_json(name: str) -> dict[str, Any] | list[Any]:
    path = OUTPUT_DIR / name
    if not path.exists():
        st.warning(f"Missing required output file: {name}")
        return {}

    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover - UI-friendly error
        st.error(f"Could not parse {name}: {exc}")
        return {}


def _money(value: float) -> str:
    return f"${value:,.0f}"


discovery = read_json("discovery_output.json")
waste = read_json("waste_findings.json")
renewal = read_json("renewal_intelligence_output.json")
scenario = read_json("scenario_comparison_output.json")
savings = read_json("top_savings_opportunities.json")
executive = read_json("executive_summary.json")

st.title("Infra Spend Intelligence - Executive Decision Center")
st.caption("Agentic control tower for spend optimization, contract risk, and strategic action planning")

overview_tab, savings_tab, scenario_tab, summary_tab = st.tabs(
    ["Overview", "Savings Opportunities", "Scenario Comparison", "Executive Summary"]
)

with overview_tab:
    total_spend = float((discovery or {}).get("total_annual_spend", 0) or 0)
    potential_savings = float((waste or {}).get("total_potential_annual_savings", 0) or 0)

    renewal_summary = (renewal or {}).get("summary", {}) if isinstance(renewal, dict) else {}
    contracts_at_risk = int(renewal_summary.get("high_risk_contracts", 0) or 0)
    upcoming_renewals = int(renewal_summary.get("contracts_renewing_within_90_days", 0) or 0)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Spend", _money(total_spend))
    col2.metric("Potential Savings", _money(potential_savings))
    col3.metric("Contracts at Risk", contracts_at_risk)
    col4.metric("Upcoming Renewals (90d)", upcoming_renewals)

    st.subheader("Renewal Risk Snapshot")
    renewal_items = (renewal or {}).get("renewal_risks", []) if isinstance(renewal, dict) else []
    if renewal_items:
        renewal_df = pd.DataFrame(renewal_items)
        st.dataframe(
            renewal_df[["contract_id", "renewal_date", "days_remaining", "risk", "recommended_action"]],
            use_container_width=True,
        )
    else:
        st.info("No renewal risk data available yet. Run renewal_intelligence_agent.py.")

with savings_tab:
    st.subheader("Top Opportunities")
    savings_items = savings if isinstance(savings, list) else []

    if savings_items:
        savings_df = pd.DataFrame(savings_items)
        st.dataframe(
            savings_df[["rank", "asset_id", "recommendation", "annual_savings", "confidence"]],
            use_container_width=True,
        )

        st.subheader("Annual Savings by Top 10")
        top10 = savings_df.head(10).copy()
        st.bar_chart(top10.set_index("asset_id")["annual_savings"])
    else:
        st.info("No savings opportunities available yet. Run savings_opportunity_agent.py.")

with scenario_tab:
    st.subheader("Keep vs Cancel vs Renegotiate")
    scenario_rows = (scenario or {}).get("scenario_results", []) if isinstance(scenario, dict) else []

    if scenario_rows:
        scenario_df = pd.DataFrame(scenario_rows)
        st.dataframe(
            scenario_df[
                [
                    "contract",
                    "keep_cost",
                    "cancel_cost",
                    "renegotiate_cost",
                    "projected_savings",
                    "recommendation",
                ]
            ],
            use_container_width=True,
        )

        chart_df = scenario_df[["contract", "keep_cost", "cancel_cost", "renegotiate_cost"]].set_index("contract")
        st.bar_chart(chart_df)
    else:
        st.info("No scenario data available yet. Run scenario_comparison_agent.py.")

with summary_tab:
    st.subheader("AI-Generated Executive Narrative")
    if isinstance(executive, dict) and executive:
        st.write(executive.get("executive_summary", "Executive summary not available."))

        st.markdown("### Top Risks")
        for item in executive.get("top_risks", []):
            st.write(f"- {item}")

        st.markdown("### Immediate Actions")
        for item in executive.get("immediate_actions", []):
            st.write(f"- {item}")

        st.markdown("### Recommended Next Steps")
        for item in executive.get("recommended_next_steps", []):
            st.write(f"- {item}")
    else:
        st.info("No executive summary available yet. Run executive_summary_agent.py.")
